BEGIN;

TRUNCATE
  noteful_notes,
  noteful_folders
    RESTART IDENTITY CASCADE;

INSERT INTO noteful_folders (name)
VALUES
  ('Important'),
  ('Super'),
  ('Spangley');

INSERT INTO noteful_notes (name, folderId, content)
VALUES
  ('Dogs', '1', 'Animus contrariis disputando gustare, nonummy nostri posuere quale ultimum. Accedere debet iriure numeranda quicquid rebum seiungi venire. Accusator audire cuius eorumque, inanitate putat quietem sicut sollicitudin. Paulo probes reprehenderit scientia sublata superstitione.\n\nArgumentum gaudere lineam nisi. Accusantibus adversa cyrenaicos desistunt docti, eaque ferre maerores pertinerent possim primis reprehendunt. Aeterno animal conformavit corporis curae, etenim invenire operam publicam tanta vitiis zenonem. Expectant fidelissimae graecum legendi, maximasque occaecat omnes referri. Censes distrahi falso necessariam nunc retinere.'),
  ('Birds', '1', 'Animus contrariis disputando gustare, nonummy nostri posuere quale ultimum. Accedere debet iriure numeranda quicquid rebum seiungi venire. Accusator audire cuius eorumque, inanitate putat quietem sicut sollicitudin. Paulo probes reprehenderit scientia sublata superstitione.\n\nArgumentum gaudere lineam nisi. Accusantibus adversa cyrenaicos desistunt docti, eaque ferre maerores pertinerent possim primis reprehendunt. Aeterno animal conformavit corporis curae, etenim invenire operam publicam tanta vitiis zenonem. Expectant fidelissimae graecum legendi, maximasque occaecat omnes referri. Censes distrahi falso necessariam nunc retinere.'),
  ('Bears', '1', 'Animus contrariis disputando gustare, nonummy nostri posuere quale ultimum. Accedere debet iriure numeranda quicquid rebum seiungi venire. Accusator audire cuius eorumque, inanitate putat quietem sicut sollicitudin. Paulo probes reprehenderit scientia sublata superstitione.\n\nArgumentum gaudere lineam nisi. Accusantibus adversa cyrenaicos desistunt docti, eaque ferre maerores pertinerent possim primis reprehendunt. Aeterno animal conformavit corporis curae, etenim invenire operam publicam tanta vitiis zenonem. Expectant fidelissimae graecum legendi, maximasque occaecat omnes referri. Censes distrahi falso necessariam nunc retinere.'),
  ('Lions', '1', 'Animus contrariis disputando gustare, nonummy nostri posuere quale ultimum. Accedere debet iriure numeranda quicquid rebum seiungi venire. Accusator audire cuius eorumque, inanitate putat quietem sicut sollicitudin. Paulo probes reprehenderit scientia sublata superstitione.\n\nArgumentum gaudere lineam nisi. Accusantibus adversa cyrenaicos desistunt docti, eaque ferre maerores pertinerent possim primis reprehendunt. Aeterno animal conformavit corporis curae, etenim invenire operam publicam tanta vitiis zenonem. Expectant fidelissimae graecum legendi, maximasque occaecat omnes referri. Censes distrahi falso necessariam nunc retinere.'),
  ('Bats', '1', 'Animus contrariis disputando gustare, nonummy nostri posuere quale ultimum. Accedere debet iriure numeranda quicquid rebum seiungi venire. Accusator audire cuius eorumque, inanitate putat quietem sicut sollicitudin. Paulo probes reprehenderit scientia sublata superstitione.\n\nArgumentum gaudere lineam nisi. Accusantibus adversa cyrenaicos desistunt docti, eaque ferre maerores pertinerent possim primis reprehendunt. Aeterno animal conformavit corporis curae, etenim invenire operam publicam tanta vitiis zenonem. Expectant fidelissimae graecum legendi, maximasque occaecat omnes referri. Censes distrahi falso necessariam nunc retinere.'),
  ('Cats', '2', 'Animus contrariis disputando gustare, nonummy nostri posuere quale ultimum. Accedere debet iriure numeranda quicquid rebum seiungi venire. Accusator audire cuius eorumque, inanitate putat quietem sicut sollicitudin. Paulo probes reprehenderit scientia sublata superstitione.\n\nArgumentum gaudere lineam nisi. Accusantibus adversa cyrenaicos desistunt docti, eaque ferre maerores pertinerent possim primis reprehendunt. Aeterno animal conformavit corporis curae, etenim invenire operam publicam tanta vitiis zenonem. Expectant fidelissimae graecum legendi, maximasque occaecat omnes referri. Censes distrahi falso necessariam nunc retinere.'),
  ('Pigs', '2', 'Animus contrariis disputando gustare, nonummy nostri posuere quale ultimum. Accedere debet iriure numeranda quicquid rebum seiungi venire. Accusator audire cuius eorumque, inanitate putat quietem sicut sollicitudin. Paulo probes reprehenderit scientia sublata superstitione.\n\nArgumentum gaudere lineam nisi. Accusantibus adversa cyrenaicos desistunt docti, eaque ferre maerores pertinerent possim primis reprehendunt. Aeterno animal conformavit corporis curae, etenim invenire operam publicam tanta vitiis zenonem. Expectant fidelissimae graecum legendi, maximasque occaecat omnes referri. Censes distrahi falso necessariam nunc retinere.'),
  ('Horses', '2', 'Animus contrariis disputando gustare, nonummy nostri posuere quale ultimum. Accedere debet iriure numeranda quicquid rebum seiungi venire. Accusator audire cuius eorumque, inanitate putat quietem sicut sollicitudin. Paulo probes reprehenderit scientia sublata superstitione.\n\nArgumentum gaudere lineam nisi. Accusantibus adversa cyrenaicos desistunt docti, eaque ferre maerores pertinerent possim primis reprehendunt. Aeterno animal conformavit corporis curae, etenim invenire operam publicam tanta vitiis zenonem. Expectant fidelissimae graecum legendi, maximasque occaecat omnes referri. Censes distrahi falso necessariam nunc retinere.'),
  ('Elephants', '2', 'Animus contrariis disputando gustare, nonummy nostri posuere quale ultimum. Accedere debet iriure numeranda quicquid rebum seiungi venire. Accusator audire cuius eorumque, inanitate putat quietem sicut sollicitudin. Paulo probes reprehenderit scientia sublata superstitione.\n\nArgumentum gaudere lineam nisi. Accusantibus adversa cyrenaicos desistunt docti, eaque ferre maerores pertinerent possim primis reprehendunt. Aeterno animal conformavit corporis curae, etenim invenire operam publicam tanta vitiis zenonem. Expectant fidelissimae graecum legendi, maximasque occaecat omnes referri. Censes distrahi falso necessariam nunc retinere.'),
  ('Turtles', '2', 'Animus contrariis disputando gustare, nonummy nostri posuere quale ultimum. Accedere debet iriure numeranda quicquid rebum seiungi venire. Accusator audire cuius eorumque, inanitate putat quietem sicut sollicitudin. Paulo probes reprehenderit scientia sublata superstitione.\n\nArgumentum gaudere lineam nisi. Accusantibus adversa cyrenaicos desistunt docti, eaque ferre maerores pertinerent possim primis reprehendunt. Aeterno animal conformavit corporis curae, etenim invenire operam publicam tanta vitiis zenonem. Expectant fidelissimae graecum legendi, maximasque occaecat omnes referri. Censes distrahi falso necessariam nunc retinere.'),
  ('Zebras', '2', 'Animus contrariis disputando gustare, nonummy nostri posuere quale ultimum. Accedere debet iriure numeranda quicquid rebum seiungi venire. Accusator audire cuius eorumque, inanitate putat quietem sicut sollicitudin. Paulo probes reprehenderit scientia sublata superstitione.\n\nArgumentum gaudere lineam nisi. Accusantibus adversa cyrenaicos desistunt docti, eaque ferre maerores pertinerent possim primis reprehendunt. Aeterno animal conformavit corporis curae, etenim invenire operam publicam tanta vitiis zenonem. Expectant fidelissimae graecum legendi, maximasque occaecat omnes referri. Censes distrahi falso necessariam nunc retinere.'),
  ('Tigers', '3', 'Animus contrariis disputando gustare, nonummy nostri posuere quale ultimum. Accedere debet iriure numeranda quicquid rebum seiungi venire. Accusator audire cuius eorumque, inanitate putat quietem sicut sollicitudin. Paulo probes reprehenderit scientia sublata superstitione.\n\nArgumentum gaudere lineam nisi. Accusantibus adversa cyrenaicos desistunt docti, eaque ferre maerores pertinerent possim primis reprehendunt. Aeterno animal conformavit corporis curae, etenim invenire operam publicam tanta vitiis zenonem. Expectant fidelissimae graecum legendi, maximasque occaecat omnes referri. Censes distrahi falso necessariam nunc retinere.'),
  ('Wolves', '3', 'Animus contrariis disputando gustare, nonummy nostri posuere quale ultimum. Accedere debet iriure numeranda quicquid rebum seiungi venire. Accusator audire cuius eorumque, inanitate putat quietem sicut sollicitudin. Paulo probes reprehenderit scientia sublata superstitione.\n\nArgumentum gaudere lineam nisi. Accusantibus adversa cyrenaicos desistunt docti, eaque ferre maerores pertinerent possim primis reprehendunt. Aeterno animal conformavit corporis curae, etenim invenire operam publicam tanta vitiis zenonem. Expectant fidelissimae graecum legendi, maximasque occaecat omnes referri. Censes distrahi falso necessariam nunc retinere.'),
  ('Monkeys', '3', 'Animus contrariis disputando gustare, nonummy nostri posuere quale ultimum. Accedere debet iriure numeranda quicquid rebum seiungi venire. Accusator audire cuius eorumque, inanitate putat quietem sicut sollicitudin. Paulo probes reprehenderit scientia sublata superstitione.\n\nArgumentum gaudere lineam nisi. Accusantibus adversa cyrenaicos desistunt docti, eaque ferre maerores pertinerent possim primis reprehendunt. Aeterno animal conformavit corporis curae, etenim invenire operam publicam tanta vitiis zenonem. Expectant fidelissimae graecum legendi, maximasque occaecat omnes referri. Censes distrahi falso necessariam nunc retinere.');

COMMIT;